### ISSUE TITLE
When to add support for RE4R

### ISSUE THREAD

**Issue by FLYzzzzzzZZZZZZ** [Backporter/RE-PAK#2] opened 2023-03-27 05:11 UTC

**Comment by Backporter** [comment] 2023-04-09 16:37
not a issue nor bug, the PAK format didn't change in RE4 and is unlikely to change, for future reference, create a issue on tool causing issues, I'm more likely to see it.

closing this report as this is not a bug report.

EDIT: if you are talking about the game selection panel, you can select whatever game you want, it doesn't really matter much, the game selection only changes a few things internally in the tool that don't really matter for skipping to PAK creation, and if you do need to extract RE4 files, just provide it the list manually with any game selected and it'll work fine.

**Closed as completed by Backporter** 2023-04-09 16:37 UTC
